### ISSUE TITLE
Pure Annotation-based approach?

### ISSUE THREAD

**Issue by kastork** [divinespear/jpa-schema-gradle-plugin#14]
Is there a way to use this plugin if the project is something like a Spring Data project that defines everything with java config? (i.e., when there is no 'persistence.xml')

**Comment by divinespear** [comment]
I researched short time, especially spring-data with spring-boot. **spring-data** approches this as *hack*, so will I.

sadly, I have no time to improve this. but I'll make time for this soon (with some beers maybe :P).

**Comment by divinespear** [comment]
I want this works well as real space :)
