### ISSUE TITLE
provide sorted schema export

### ISSUE THREAD

**Issue by blackdrag** [divinespear/jpa-schema-gradle-plugin#23]
We are using the generated schema during build to ensure there are no schema changes left to put into migration scripts. So basically we compare the old schema against the new and fail the build if they are different. But this worked well for a while, but it seems the output is not really ordered. So suddenly columns are in a different order and the build fails. I have no problem with the statements itself being in a different order, I can easily sort that myself. But the columns and especially the primary key definitions would require me writing a small parser. Would be nice to have this as part of the plugin

**Comment by divinespear** [comment]
It's bad, cause this is JPA problem.
When I get some rest time, maybe I'll find some solutions, It will opened again.
